services:
    tf-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TERRAFORM_VERSION: "1.13.3"
                INSTALL_AZURE_CLI: "YES"
                INSTALL_AWS_CLI: "YES"
        container_name: terraform_env
        platform: linux/amd64
        volumes:
            - ./iac/:/iac
            - ./scripts/:/scripts
            - ./.aws/:/.aws
        working_dir: /iac/

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        platform: linux/amd64
        container_name: backend
        ports:
            - "8000:80"
        environment:
            - ENVIRONMENT=local

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        platform: linux/amd64
        container_name: react_frontend
        ports:
            - "80:80"
        environment:
            
            
            - API_URL=http://backend:80/info
        depends_on:
            - backend
